### ISSUE TITLE
Example penetrator shaders have incorrect vertex output values

### ISSUE THREAD

**Issue by LostToPixels** [naelstrof/UnityPenetrationTech#6]
Upon importing, all values are set as Relative values instead of Absolute, causing objects to draw twice the size of the mesh.
![Screenshot 2022-12-23 194607](https://user-images.githubusercontent.com/121353365/209444941-ccb3371c-b170-4dcf-b54e-5d117f81ce82.png)

**Comment by naelstrof** [comment]
Oh shoot, I didn't realize my examples had the incorrect settings haha. Whoops!
