### ISSUE TITLE
(QOL) Ability to draw Penetratable gizmos on penetration

### ISSUE THREAD

**Issue by LostToPixels** [naelstrof/UnityPenetrationTech#7]
(Regardless of whether they are selected or not)
Could exist as some sort of toggle or something, would be very useful for debugging at design time when testing in editor (Penetrator selected, upon connection with Penetratable, penetratable listener gizmos are then drawn).

**Comment by naelstrof** [comment]
I want to ask a question about how *every* unity script that uses `OnDrawGizmosSelected()` suffers from this issue.

It makes me wonder if there's already a built-in way to do this in Unity-- does spawning a new Inspector window and locking it to the penetrable/penetrator cause it to permanently show its gizmos?

If not, then yeah I suppose there should be a way to toggle them on.
