### ISSUE TITLE
Similar function as SetTargetHole but with lerp transition

### ISSUE THREAD

**Issue by Kovacs-3d** [naelstrof/UnityPenetrationTech#8]
I am making an alternative hole detector in listeners. Auto penerate is therefore switched off. The listeners perform the Penetrate function.
I am looking for a function like SetTargetHole but it would not be affected by the Peneration Margin Of Error value.
I could give him the lerp value.
I would think something like this SetTargetHoleLerp(Penetrable target, float lerp).
Would be 0 in normal mode and 1 when turning fully towards the target.
I don't know if it's clear, but can you help me if it's not too much trouble?

**Comment by naelstrof** [comment]
Ooh, I believe I understand, and yeah I think the whole penetration detection system needs to be refactored.

I think I understand what you're saying though, the ability to discretely set the lerp value like that would be nice.

**Comment by Kovacs-3d** [comment]
I will share my script to make it clearer why I wrote it.
[Script](https://drive.google.com/file/d/15apxKFwRwZGQYehaycPh8yJYiM5b2s2R/view?usp=share_link)
And a short video of how it works.
[Video](https://drive.google.com/file/d/1PlUhmLRvpYIiZUJtAlM4Sbk3CLGAxmFO/view?usp=share_link)
Actually I wrote it because as you can see in the video when it penetrates there is no transition, it jumps there. There is an automatic transition when pulling out, I would like to have this transition when start penetrating.
