### ISSUE TITLE
Script execution order: curse of unity's "packages"

### ISSUE THREAD

**Issue by nakedfighter3d** [naelstrof/UnityPenetrationTech#9]
While working with a procedural animation you often need to define a precise "script execution order". To set a proper order of IK solver, dynamic bones, additive motion, etc. And yes, for penetrator you also need to set execution order to make sure it will be run after the IK pass _(or you will get a weird, broken calculation)_. Unfortunatley, it's impossible to set execution order for scripts in unity's "Packages", because they are "read only" by design. For now I'm using a turnaround that include: find a *.meta file for penetrator script in /Library folder and edit it manually which is... well, not really sustainable way. I would appreciate any idea on how it can be solved properly

**Comment by naelstrof** [comment]
Ah yeah, the solution in this case would be to fork the project, then make your desired edits, then simply check out your fork instead.

It sucks that script execution order isn't a project specific setting, and I fear it would have consequences to change it natively as I already use this package as-is in many of my projects.

**Comment by nakedfighter3d** [comment]
Blame Unity! But yeah, still a tricky solution that will make updates harder. So I probably better stick with my "manually edit the library" tweak while it's at least somehow working.
